version: "0.0.1"
services:
  postgres:
    container_name: postgres-learn
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123yuling
      POSTGRES_USERNAME: yuling